AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hemp Conduit Good Handler
Parameters:
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs that Lambda will use
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC Subnet IDs that Lambda will use (min 2 for HA)
Resources:
  handler:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: go1.x
      Handler: handler
      CodeUri: .
      Timeout: 30
      Policies:
      - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds: SecurityGroupIds
        SubnetIds: VpcSubnetIds
Outputs:
  hcGoodHandler:
    Description: Lambda ARN
    Value: HelloWorldFunction.Arn
